### ISSUE TITLE
Support for Seene variation of the same?

### ISSUE THREAD

**Issue by neopaf** [spite/android-lens-blur-depth-extractor#3]
(was referred to this project by Sketchfab support team)

I've tried to import some of my Seene-app (iOS) export format, which Creators claim is same as Google Lens Blur format.
But failed.

Please quick-look is the format is totally broken = unsupportable.
Maybe there is something simple to be changed = fixed?

Attaching some examples.
![img_4027](https://cloud.githubusercontent.com/assets/4362564/17191266/34d701b6-545a-11e6-9399-5e35c41058fe.JPG)
![img_4026](https://cloud.githubusercontent.com/assets/4362564/17191268/3509083c-545a-11e6-8829-6f8a105916a0.JPG)
![img_4025](https://cloud.githubusercontent.com/assets/4362564/17191267/35063c38-545a-11e6-9441-b069def5d258.JPG)

**Comment by neopaf** [comment]
@zettlerm, hello

**Comment by spite** [comment]
It seems like they've stripped the GDepth:Data attribute from the file. Other attributes are there, but the actual depth is nowhere to be found.

Here's a snapshot of an hex view of one of the files provided. You'll see there's GDepth:Format/Near/Far but no Data:

<img width="1392" alt="screen shot 2016-07-28 at 00 42 24" src="https://cloud.githubusercontent.com/assets/731885/17195124/603f203e-545c-11e6-8fec-ecd88b27d4e2.png">

Who have you contacted from Seene that told you about compatibility? Could you ask them about this issue?

**Comment by neopaf** [comment]
I will.
I'm a developer myself, but not very deep into .JPEG format or ways to hide XMP there.

But I see some 2 (two!) XMP sections there, and one of them seem to have the data.
Used this tool to extract it: http://www.sno.phy.queensu.ca/~phil/exiftool/

Attached:
[35063c38-545a-11e6-9441-b069def5d258-exif.txt](https://github.com/spite/android-lens-blur-depth-extractor/files/387864/35063c38-545a-11e6-9441-b069def5d258-exif.txt)

I did try to convert that BASE64 and it seems to have what's needed:
![35063c38-545a-11e6-9441-b069def5d258-depth](https://cloud.githubusercontent.com/assets/4362564/17204570/391c2b04-54b7-11e6-8670-043cf574c323.png)

What would you say?
Maybe data got into second XMP and it is still possible to extract & use it?

**Comment by seene-club** [comment]
Hello,

verified with [Seene-Toolkit](https://github.com/seene-club/seene-toolkit) that XMP is there.
You'll find the depthmap in the section **GDepth:Data**

![screenhunter_271 jul 28 12 17](https://cloud.githubusercontent.com/assets/11654139/17209604/2ab0d9e6-54be-11e6-86d9-2ace2b5a08a9.jpg)
![screenhunter_272 jul 28 12 19](https://cloud.githubusercontent.com/assets/11654139/17209613/35d24fb2-54be-11e6-9563-4048a040ea68.jpg)

hope that information is helpful!
cheers,
Mathias

**Comment by spite** [comment]
Ah, Ok. Couple of things here...

- I downloaded the file and the preview in github probably strips those headers. If I download the image from githubusercontent.com I can see that GDepth:Data is there.

- The library is correctly loading the depth data. What is failing silently -because I didn't know that could happen- is that there's no GImage:Mime nor GImage:Data in the XMP block. That is, there is no info about the image. I'm going to change it so it can display the color buffer too shortly.

**Comment by spite** [comment]
Ok, fixed. The lib is updated -make sure you check index.html on how to load the color buffer now-. 

The tool https://www.clicktorelease.com/tools/lens-blur-depth-extractor/
and the player https://www.clicktorelease.com/code/depth-player/
are updated too.

Thanks!

**Comment by seene-club** [comment]
The Seene format loads now! Great work, Jaume. Thank you very much!

But one more thing. There are so less points in the point cloud (wireframe too).
Your examples look much better. Tried the sliders on the right, but did not got more depth points.
Any idea?

![screenhunter_273 jul 28 14 35](https://cloud.githubusercontent.com/assets/11654139/17212946/3c04bfdc-54d2-11e6-95e1-d6717678b4ef.jpg)
![screenhunter_274 jul 28 14 35](https://cloud.githubusercontent.com/assets/11654139/17212949/42739654-54d2-11e6-842f-31e4cc6ce4c4.jpg)
![screenhunter_275 jul 28 14 36](https://cloud.githubusercontent.com/assets/11654139/17212954/4892ac82-54d2-11e6-9017-76b2bd061c5d.jpg)
![screenhunter_276 jul 28 14 44](https://cloud.githubusercontent.com/assets/11654139/17212961/4da3cb98-54d2-11e6-9dc1-24ba75d21c20.jpg)

**Comment by spite** [comment]
Yes, the mesh size/tessellation is based on the image size. Lens Blur images are usually pretty large, but the seene ones seem to report to be 240x240, so the mesh is much smaller. Use the Quad Side parameter on the viewer, set it to 1, and you'll have more quads. Changing the filter might help, too.

**Comment by spite** [comment]
Now I've also realised that 240x240 is the reported size of the Depth Map. Will fix, too.

**Comment by spite** [comment]
Fixed.

**Comment by seene-club** [comment]
Awesome, Jaume. Seenes look great now with your viewer. You made my day!
Thank you very much for the fantastic work!

![screenhunter_278 jul 28 15 51](https://cloud.githubusercontent.com/assets/11654139/17214948/7df98be4-54db-11e6-995d-ba699518c568.jpg)
![screenhunter_279 jul 28 15 51](https://cloud.githubusercontent.com/assets/11654139/17214956/83a7670a-54db-11e6-9f60-b2a40cdca646.jpg)
![screenhunter_280 jul 28 15 51](https://cloud.githubusercontent.com/assets/11654139/17214963/8bf54328-54db-11e6-82f9-a0e815fb02a8.jpg)

**Comment by spite** [comment]
Great! Thanks for the feedback and the nice photos for testing!

**Comment by neopaf** [comment]
Jaume, thank you very much.
This was fast, and very pleasant.
Thank you very much for your effort and for hosting of this.
We were directed to you by Sketchfab support people.

I've found one more detail, will file as a separate issue.

**Comment by neopaf** [comment]
Jaume, is depth map is (240 × 240) and main image (1936 × 1936)
somehow related to Quad?

Maybe Quad is just "take each N-th point from depthmap?"
1=take every point
2=take one, ignore one point
3=take one, ignore two points
?
